### ISSUE TITLE
can't use as template

### ISSUE THREAD

**Issue by asifzubair** [snakemake-workflows/single-cell-rna-seq#8]
Got this message from GitHub when trying to use this repo as a template:

>We're sorry, something went wrong.
>We were unable to clone snakemake-workflows/single-cell-rna-seq's contents into asifzubair/snakemake-scrnaseq. The template you used includes files that are larger than 10 megabytes. Please ask snakemake-workflows to remove those files from the template and try again.

**Comment by johanneskoester** [comment]
Thanks! Should be fixed now!

**Comment by johanneskoester** [comment]
Thanks! Should be fixed now!

**Comment by asifzubair** [comment]
Thanks, @johanneskoester . Would it possible to get hold of the test data you use to generate the example report? Much appreciated!
